import { DatabaseSchema } from '../lib/types';

export const seedData: DatabaseSchema = {
  meta: {
    appVersion: '1.0.0',
    exportDate: new Date().toISOString(),
    userCurrency: '₹',
    organizationName: 'Demo Store',
  },
  collections: [
    {
      id: '1',
      name: 'Electronics',
      description: 'Electronic items and accessories',
      schema: [
        {
          key: 'name',
          label: 'Product Name',
          type: 'text',
          required: true,
        },
        {
          key: 'brand',
          label: 'Brand',
          type: 'text',
          required: true,
        },
        {
          key: 'price',
          label: 'Price',
          type: 'currency',
          required: true,
        },
        {
          key: 'quantity',
          label: 'Quantity',
          type: 'number',
          required: true,
          defaultValue: 0,
        },
        {
          key: 'category',
          label: 'Category',
          type: 'select',
          options: ['Mobile', 'Laptop', 'Tablet', 'Accessories'],
        },
        {
          key: 'inStock',
          label: 'In Stock',
          type: 'boolean',
          defaultValue: true,
        },
      ],
      data: [
        {
          id: '101',
          createdAt: new Date('2024-12-01').toISOString(),
          values: {
            name: 'iPhone 15 Pro',
            brand: 'Apple',
            price: 129900,
            quantity: 5,
            category: 'Mobile',
            inStock: true,
          },
        },
        {
          id: '102',
          createdAt: new Date('2024-12-02').toISOString(),
          values: {
            name: 'MacBook Air M2',
            brand: 'Apple',
            price: 114900,
            quantity: 3,
            category: 'Laptop',
            inStock: true,
          },
        },
        {
          id: '103',
          createdAt: new Date('2024-12-03').toISOString(),
          values: {
            name: 'Samsung Galaxy S24',
            brand: 'Samsung',
            price: 74999,
            quantity: 8,
            category: 'Mobile',
            inStock: true,
          },
        },
        {
          id: '104',
          createdAt: new Date('2024-12-04').toISOString(),
          values: {
            name: 'iPad Pro 11"',
            brand: 'Apple',
            price: 81900,
            quantity: 2,
            category: 'Tablet',
            inStock: true,
          },
        },
        {
          id: '105',
          createdAt: new Date('2024-12-05').toISOString(),
          values: {
            name: 'AirPods Pro',
            brand: 'Apple',
            price: 24900,
            quantity: 15,
            category: 'Accessories',
            inStock: true,
          },
        },
      ],
    },
    {
      id: '2',
      name: 'Clothing',
      description: 'Apparel and fashion items',
      schema: [
        {
          key: 'itemName',
          label: 'Item Name',
          type: 'text',
          required: true,
        },
        {
          key: 'size',
          label: 'Size',
          type: 'select',
          options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
          required: true,
        },
        {
          key: 'color',
          label: 'Color',
          type: 'text',
        },
        {
          key: 'price',
          label: 'Price',
          type: 'currency',
          required: true,
        },
        {
          key: 'stock',
          label: 'Stock',
          type: 'number',
          defaultValue: 0,
        },
      ],
      data: [
        {
          id: '201',
          createdAt: new Date('2024-12-01').toISOString(),
          values: {
            itemName: 'Cotton T-Shirt',
            size: 'M',
            color: 'Blue',
            price: 499,
            stock: 25,
          },
        },
        {
          id: '202',
          createdAt: new Date('2024-12-02').toISOString(),
          values: {
            itemName: 'Denim Jeans',
            size: 'L',
            color: 'Black',
            price: 1499,
            stock: 12,
          },
        },
        {
          id: '203',
          createdAt: new Date('2024-12-03').toISOString(),
          values: {
            itemName: 'Hoodie',
            size: 'XL',
            color: 'Gray',
            price: 1999,
            stock: 8,
          },
        },
      ],
    },
    {
      id: '3',
      name: 'Groceries',
      description: 'Food and household items',
      schema: [
        {
          key: 'product',
          label: 'Product Name',
          type: 'text',
          required: true,
        },
        {
          key: 'weight',
          label: 'Weight/Volume',
          type: 'text',
        },
        {
          key: 'price',
          label: 'Price',
          type: 'currency',
          required: true,
        },
        {
          key: 'expiryDate',
          label: 'Expiry Date',
          type: 'date',
        },
        {
          key: 'stock',
          label: 'Stock',
          type: 'number',
          defaultValue: 0,
        },
      ],
      data: [
        {
          id: '301',
          createdAt: new Date('2024-12-01').toISOString(),
          values: {
            product: 'Rice',
            weight: '5kg',
            price: 350,
            expiryDate: new Date('2025-12-31').toISOString(),
            stock: 50,
          },
        },
        {
          id: '302',
          createdAt: new Date('2024-12-02').toISOString(),
          values: {
            product: 'Cooking Oil',
            weight: '1L',
            price: 180,
            expiryDate: new Date('2025-06-30').toISOString(),
            stock: 30,
          },
        },
        {
          id: '303',
          createdAt: new Date('2024-12-03').toISOString(),
          values: {
            product: 'Milk',
            weight: '1L',
            price: 60,
            expiryDate: new Date('2025-01-15').toISOString(),
            stock: 40,
          },
        },
      ],
    },
  ],
  ledger: [
    {
      organization: {
        id: 'org1',
        name: 'Rajesh Electronics',
        phone: '+91 98765 43210',
        email: 'rajesh@electronics.com',
      },
      transactions: [
        {
          id: 'txn101',
          organizationId: 'org1',
          type: 'DEBIT',
          amount: 50000,
          date: new Date('2024-11-15').toISOString(),
          remark: 'Purchase of 5 iPhones',
          tags: ['wholesale', 'electronics'],
        },
        {
          id: 'txn102',
          organizationId: 'org1',
          type: 'CREDIT',
          amount: 20000,
          date: new Date('2024-11-20').toISOString(),
          remark: 'Partial payment received',
          tags: ['payment'],
        },
        {
          id: 'txn103',
          organizationId: 'org1',
          type: 'DEBIT',
          amount: 15000,
          date: new Date('2024-12-01').toISOString(),
          remark: 'Additional purchase - Accessories',
          tags: ['wholesale', 'accessories'],
        },
      ],
    },
    {
      organization: {
        id: 'org2',
        name: 'Sharma Textiles',
        phone: '+91 99887 76655',
        email: 'contact@sharmatextiles.com',
      },
      transactions: [
        {
          id: 'txn201',
          organizationId: 'org2',
          type: 'DEBIT',
          amount: 30000,
          date: new Date('2024-11-10').toISOString(),
          remark: 'Fabric order for winter collection',
          tags: ['wholesale', 'fabric'],
        },
        {
          id: 'txn202',
          organizationId: 'org2',
          type: 'CREDIT',
          amount: 30000,
          date: new Date('2024-11-25').toISOString(),
          remark: 'Full payment received',
          tags: ['payment', 'settled'],
        },
      ],
    },
    {
      organization: {
        id: 'org3',
        name: 'Kumar Groceries',
        phone: '+91 98123 45678',
      },
      transactions: [
        {
          id: 'txn301',
          organizationId: 'org3',
          type: 'DEBIT',
          amount: 5000,
          date: new Date('2024-12-01').toISOString(),
          remark: 'Rice and oil purchase',
          tags: ['groceries'],
        },
        {
          id: 'txn302',
          organizationId: 'org3',
          type: 'CREDIT',
          amount: 2000,
          date: new Date('2024-12-05').toISOString(),
          remark: 'Partial payment',
          tags: ['payment'],
        },
      ],
    },
    {
      organization: {
        id: 'org4',
        name: 'Patel Traders',
        phone: '+91 97654 32109',
        email: 'info@pateltraders.in',
      },
      transactions: [
        {
          id: 'txn401',
          organizationId: 'org4',
          type: 'CREDIT',
          amount: 10000,
          date: new Date('2024-11-28').toISOString(),
          remark: 'Advance payment for upcoming order',
          tags: ['advance', 'payment'],
        },
      ],
    },
    {
      organization: {
        id: 'org5',
        name: 'Singh Electronics Pvt Ltd',
        phone: '+91 96543 21098',
        email: 'sales@singhelectronics.com',
      },
      transactions: [
        {
          id: 'txn501',
          organizationId: 'org5',
          type: 'DEBIT',
          amount: 75000,
          date: new Date('2024-11-12').toISOString(),
          remark: 'Bulk purchase - Laptops and tablets',
          tags: ['wholesale', 'electronics', 'bulk'],
        },
        {
          id: 'txn502',
          organizationId: 'org5',
          type: 'CREDIT',
          amount: 25000,
          date: new Date('2024-11-18').toISOString(),
          remark: 'First installment',
          tags: ['payment', 'installment'],
        },
        {
          id: 'txn503',
          organizationId: 'org5',
          type: 'CREDIT',
          amount: 25000,
          date: new Date('2024-12-02').toISOString(),
          remark: 'Second installment',
          tags: ['payment', 'installment'],
        },
      ],
    },
  ],
};
